import json
import time
from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, Path, Request
from fastapi.responses import StreamingResponse
from langchain_core.embeddings import Embeddings
from pydantic import BaseModel

from fastrag.llms.llm import ILLM
from fastrag.serve.ask.dependencies import get_embedding_model, get_llm, get_vector_store
from fastrag.serve.chats.deps import get_chat_service
from fastrag.serve.chats.interfaces import IChatService
from fastrag.serve.chats.schemas import ChatMessageCreate
from fastrag.serve.geolocalization.deps import ClientInfo, get_client_info
from fastrag.serve.rate_limiting import limiter
from fastrag.serve.telemetry.metrics import llm_time_to_first_token
from fastrag.stores.store import IVectorStore

router = APIRouter()


class QuestionRequest(BaseModel):
    question: str


def build_prompt(context: str, question: str) -> str:
    return f"""
    You are a helpful assistant and expert in data spaces.

    Always use inline references in the form [<NUMBER OF DOCUMENT>](ref:<NUMBER OF DOCUMENT>)
    ONLY if you use information from a document. For example, if you use the information from
    Document[3], you should write [3](ref:3) at the end of the sentence where you used that
    information.
    Give a precise, accurate and structured answer without repeating the question.
    
    These are the documents:
    {context}

    Question:
    {question}

    Answer:
    """.strip()


@router.post(
    "/ask/{chat_id}",
    response_class=StreamingResponse,
)
@limiter.limit("5/minute")
async def ask_question(
    request: Request,  # Required by slowapi limiter
    req: QuestionRequest,
    chat_service: Annotated[IChatService, Depends(get_chat_service)],
    vector_store: Annotated[IVectorStore, Depends(get_vector_store)],
    embedding_model: Annotated[Embeddings, Depends(get_embedding_model)],
    llm: Annotated[ILLM, Depends(get_llm)],
    client_info: Annotated[ClientInfo, Depends(get_client_info)],
    chat_id: UUID = Path(..., description="Chat session id generated by the client"),
):
    await chat_service.save_message(
        data=ChatMessageCreate(
            chat_id=chat_id,
            content=req.question,
            role="user",
        ),
        ip=client_info.ip,
        country=client_info.country,
    )

    query_embedding = await embedding_model.aembed_query(req.question)

    results = await vector_store.similarity_search(
        query=req.question,
        query_embedding=query_embedding,
        k=5,
    )
    context_parts = [f"Document[{i}]: {doc.page_content}" for i, doc in enumerate(results)]
    context = "\n\n".join(context_parts)
    sources_metadata: list = [doc.metadata.get("source") for doc in results]

    start_time = time.monotonic()
    first_token_time = None

    answer = ""

    async def generate():
        nonlocal first_token_time, answer

        yield f"data: {json.dumps({'type': 'sources', 'data': sources_metadata})}\n\n"

        prompt = build_prompt(context, req.question)

        async for token in llm.stream(prompt):
            if first_token_time is None:
                first_token_time = time.monotonic()
                llm_time_to_first_token.record(first_token_time - start_time, {})
            answer += token
            yield f"data: {json.dumps({'type': 'token', 'data': token})}\n\n"
        await chat_service.save_message(
            data=ChatMessageCreate(
                chat_id=chat_id,
                content=answer,
                role="assistant",
                sources=sources_metadata,
            )
        )

    return StreamingResponse(
        content=generate(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
