from collections.abc import Sequence
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field


class QuestionRequest(BaseModel):
    question: str
    chat_id: UUID | None = Field(None, description="Chat session id generated by the client")


class QuestionResponse(BaseModel):
    response_type: Literal["sources", "token"] = Field(..., alias="type")
    data: str | Sequence[str]

    def encode(self, encoding: str = "utf-8", errors: str = "strict") -> bytes:
        payload = f"data: {self.model_dump_json(by_alias=True)}\n\n"
        return payload.encode(encoding, errors)
