import { AppSidebar } from "@/components/app-sidebar"
import { ThemeProvider } from "@/providers/theme-provider"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import ThemeCookieSetter from "@/components/theme-cookie-setter"
import "@/styles/globals.css"
import type { Metadata } from "next"
import { NextIntlClientProvider } from "next-intl"
import { cookies } from "next/dist/server/request/cookies"
import { Geist, Geist_Mono, Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main>
                <ThemeCookieSetter />
                <SidebarTrigger />
                {children}
              </main>
            </ThemeProvider>
          </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
